export { Users } from './Users'
export { Media } from './Media'
export { Categories } from './Categories'
export { Pages } from './Pages'
export { Posts } from './Posts'
export { Services } from './Services'
export { Products } from './Products'
export { Team } from './Team'
export { Portfolio } from './Portfolio'
export { Testimonials } from './Testimonials'
export { PricePackages } from './PricePackages'
export { Bookings } from './Bookings'
export { FAQ } from './FAQ'
export { ContactSubmissions } from './ContactSubmissions'
// Classes collection removed - use Services with serviceType: 'class' instead
export { Subscriptions } from './Subscriptions'
