import type { Block } from 'payload'

export const TrustBadgesBlock: Block = {
  slug: 'trust-badges',
  labels: {
    singular: 'Trust Badges',
    plural: 'Trust Badges',
  },
  imageURL: '/blocks/trust-badges.svg',
  fields: [
    {
      name: 'variant',
      type: 'select',
      label: 'Varianta',
      defaultValue: 'bar',
      options: [
        { label: 'Bara orizontala', value: 'bar' },
        { label: 'Grid 3 coloane', value: 'grid-3' },
        { label: 'Grid 4 coloane', value: 'grid-4' },
        { label: 'Iconite inline', value: 'inline' },
        { label: 'Carduri cu fundal', value: 'cards' },
        { label: 'Minimal (doar iconite)', value: 'minimal' },
      ],
    },
    {
      name: 'heading',
      type: 'text',
      label: 'Titlu sectiune',
      admin: {
        description: 'Optional - lasa gol pentru a afisa doar badge-urile',
      },
    },
    {
      name: 'source',
      type: 'select',
      label: 'Sursa date',
      defaultValue: 'preset',
      options: [
        { label: 'Preset-uri comune', value: 'preset' },
        { label: 'Continut custom', value: 'custom' },
      ],
    },
    {
      name: 'presets',
      type: 'select',
      label: 'Selecteaza badge-uri',
      hasMany: true,
      admin: {
        condition: (_, siblingData) => siblingData?.source === 'preset',
        description: 'Alege badge-urile pe care vrei sa le afisezi',
      },
      options: [
        { label: 'Livrare gratuita', value: 'free-shipping' },
        { label: 'Livrare rapida 24h', value: 'fast-shipping' },
        { label: 'Retur 30 zile', value: 'return-30' },
        { label: 'Retur 14 zile', value: 'return-14' },
        { label: 'Plata securizata', value: 'secure-payment' },
        { label: 'Garantie', value: 'warranty' },
        { label: 'Suport 24/7', value: 'support-24-7' },
        { label: 'Calitate garantata', value: 'quality' },
        { label: 'Pret corect', value: 'fair-price' },
        { label: 'Transport gratuit peste X lei', value: 'free-shipping-threshold' },
        { label: 'Experienta de peste X ani', value: 'experience-years' },
        { label: 'Clienti multumiti', value: 'happy-customers' },
        { label: 'Produse romanesti', value: 'romanian-products' },
        { label: 'Eco-friendly', value: 'eco-friendly' },
        { label: 'Consultatie gratuita', value: 'free-consultation' },
        { label: 'Programare online', value: 'online-booking' },
      ],
    },
    {
      name: 'customValues',
      type: 'group',
      label: 'Valori personalizate',
      admin: {
        condition: (_, siblingData) => siblingData?.source === 'preset',
        description: 'Completeaza valorile pentru badge-urile selectate (daca e cazul)',
      },
      fields: [
        {
          name: 'shippingThreshold',
          type: 'number',
          label: 'Transport gratuit de la (lei)',
          defaultValue: 150,
        },
        {
          name: 'experienceYears',
          type: 'number',
          label: 'Ani de experienta',
          defaultValue: 10,
        },
        {
          name: 'happyCustomersCount',
          type: 'text',
          label: 'Numar clienti multumiti',
          defaultValue: '5000+',
        },
        {
          name: 'warrantyPeriod',
          type: 'text',
          label: 'Perioada garantie',
          defaultValue: '2 ani',
        },
      ],
    },
    {
      name: 'badges',
      type: 'array',
      label: 'Badge-uri custom',
      admin: {
        condition: (_, siblingData) => siblingData?.source === 'custom',
      },
      fields: [
        {
          name: 'icon',
          type: 'select',
          label: 'Iconita',
          required: true,
          options: [
            { label: 'Camion (livrare)', value: 'Truck' },
            { label: 'Pachet', value: 'Package' },
            { label: 'Scut (securitate)', value: 'Shield' },
            { label: 'Scut cu bifa', value: 'ShieldCheck' },
            { label: 'Bifa in cerc', value: 'CheckCircle' },
            { label: 'Stea', value: 'Star' },
            { label: 'Inima', value: 'Heart' },
            { label: 'Telefon', value: 'Phone' },
            { label: 'Ceas', value: 'Clock' },
            { label: 'Calendar', value: 'Calendar' },
            { label: 'Card credit', value: 'CreditCard' },
            { label: 'Cadou', value: 'Gift' },
            { label: 'Medalie', value: 'Award' },
            { label: 'Utilizatori', value: 'Users' },
            { label: 'ThumbsUp', value: 'ThumbsUp' },
            { label: 'Frunza (eco)', value: 'Leaf' },
            { label: 'Recycle', value: 'Recycle' },
            { label: 'Refresh (retur)', value: 'RefreshCw' },
            { label: 'Headphones (support)', value: 'Headphones' },
            { label: 'MessageCircle', value: 'MessageCircle' },
            { label: 'Zap (rapid)', value: 'Zap' },
            { label: 'BadgeCheck', value: 'BadgeCheck' },
            { label: 'CircleDollarSign', value: 'CircleDollarSign' },
            { label: 'Banknote', value: 'Banknote' },
          ],
        },
        {
          name: 'title',
          type: 'text',
          label: 'Titlu',
          required: true,
        },
        {
          name: 'description',
          type: 'text',
          label: 'Descriere scurta',
        },
      ],
    },
    {
      name: 'showDescriptions',
      type: 'checkbox',
      label: 'Afiseaza descrierile',
      defaultValue: true,
      admin: {
        description: 'Debifati pentru a afisa doar iconitele si titlurile',
      },
    },
    {
      name: 'iconSize',
      type: 'select',
      label: 'Dimensiune iconite',
      defaultValue: 'medium',
      options: [
        { label: 'Mica', value: 'small' },
        { label: 'Medie', value: 'medium' },
        { label: 'Mare', value: 'large' },
      ],
    },
    {
      name: 'backgroundColor',
      type: 'select',
      label: 'Culoare fundal',
      defaultValue: 'light',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Light', value: 'light' },
        { label: 'Dark', value: 'dark' },
        { label: 'Primary', value: 'primary' },
        { label: 'Transparent', value: 'transparent' },
      ],
    },
  ],
}
