/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    services: Service;
    team: Team;
    portfolio: Portfolio;
    testimonials: Testimonial;
    'price-packages': PricePackage;
    bookings: Booking;
    faq: Faq;
    'contact-submissions': ContactSubmission;
    'product-categories': ProductCategory;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'price-packages': PricePackagesSelect<false> | PricePackagesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    theme: Theme;
    logo: Logo;
    'business-info': BusinessInfo;
    'shop-settings': ShopSetting;
    'design-variant': DesignVariant;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    logo: LogoSelect<false> | LogoSelect<true>;
    'business-info': BusinessInfoSelect<false> | BusinessInfoSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
    'design-variant': DesignVariantSelect<false> | DesignVariantSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  heroType?: ('none' | 'minimal' | 'centered' | 'withImage' | 'fullscreen' | 'split' | 'video' | 'slider') | null;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    image?: (string | null) | Media;
    videoUrl?: string | null;
    ctaButtons?:
      | {
          label: string;
          link: string;
          variant?: ('default' | 'outline' | 'ghost') | null;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | {
            variant?: ('centered' | 'left-aligned' | 'split' | 'fullscreen' | 'video' | 'minimal' | 'slider') | null;
            headline: string;
            subheadline?: string | null;
            image?: (string | null) | Media;
            videoUrl?: string | null;
            slides?:
              | {
                  image: string | Media;
                  headline?: string | null;
                  subheadline?: string | null;
                  id?: string | null;
                }[]
              | null;
            ctaButtons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('default' | 'outline' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            overlayOpacity?: ('0' | '25' | '50' | '75') | null;
            textColor?: ('auto' | 'dark' | 'light') | null;
            height?: ('small' | 'medium' | 'large' | 'fullscreen') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            variant?:
              | ('grid-3' | 'grid-4' | 'grid-2' | 'list' | 'list-alternating' | 'carousel' | 'tabs' | 'with-prices')
              | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual' | 'custom') | null;
            selectedServices?: (string | Service)[] | null;
            filterByCategory?: (string | null) | Category;
            limit?: number | null;
            onlyFeatured?: boolean | null;
            customServices?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: string | null;
                  image?: (string | null) | Media;
                  price?: number | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            showPrices?: boolean | null;
            showIcons?: boolean | null;
            ctaButton?: {
              enabled?: boolean | null;
              label?: string | null;
              link?: string | null;
            };
            backgroundColor?: ('default' | 'light' | 'dark' | 'primary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            variant?: ('grid' | 'grid-centered' | 'carousel' | 'list' | 'featured' | 'with-modal') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual') | null;
            selectedMembers?: (string | Team)[] | null;
            limit?: number | null;
            onlyFeatured?: boolean | null;
            showRole?: boolean | null;
            showBio?: boolean | null;
            showSocial?: boolean | null;
            showContact?: boolean | null;
            columns?: ('2' | '3' | '4') | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            variant?: ('carousel' | 'grid' | 'single-featured' | 'masonry' | 'cards-rotating' | 'minimal') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual') | null;
            selectedTestimonials?: (string | Testimonial)[] | null;
            limit?: number | null;
            onlyFeatured?: boolean | null;
            showRating?: boolean | null;
            showAvatar?: boolean | null;
            showSource?: boolean | null;
            autoplay?: boolean | null;
            backgroundColor?: ('default' | 'light' | 'dark' | 'primary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            variant?: ('cards-3' | 'cards-4' | 'table' | 'list' | 'toggle' | 'featured-center') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual') | null;
            selectedPackages?: (string | PricePackage)[] | null;
            limit?: number | null;
            showFeatures?: boolean | null;
            showOldPrice?: boolean | null;
            ctaText?: string | null;
            /**
             * Ex: Preturile nu includ TVA
             */
            disclaimer?: string | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            variant?:
              | ('grid-masonry' | 'grid-uniform' | 'carousel' | 'filterable' | 'lightbox' | 'case-studies')
              | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual') | null;
            selectedProjects?: (string | Portfolio)[] | null;
            filterByCategory?: (string | null) | Category;
            limit?: number | null;
            onlyFeatured?: boolean | null;
            showDescription?: boolean | null;
            showClient?: boolean | null;
            columns?: ('2' | '3' | '4') | null;
            ctaButton?: {
              enabled?: boolean | null;
              label?: string | null;
              link?: string | null;
            };
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio';
          }
        | {
            variant?: ('accordion' | 'two-columns' | 'tabs' | 'searchable' | 'numbered') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual' | 'custom') | null;
            selectedFAQs?: (string | Faq)[] | null;
            filterByCategory?: (string | null) | Category;
            limit?: number | null;
            customFAQs?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            defaultOpen?: ('none' | 'first' | 'all') | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            variant?: ('split' | 'centered' | 'with-map' | 'full-width' | 'minimal' | 'cards') | null;
            heading?: string | null;
            subheading?: string | null;
            showForm?: boolean | null;
            formFields?: {
              showName?: boolean | null;
              showEmail?: boolean | null;
              showPhone?: boolean | null;
              showSubject?: boolean | null;
              showService?: boolean | null;
              showMessage?: boolean | null;
            };
            submitButtonText?: string | null;
            successMessage?: string | null;
            showContactInfo?: boolean | null;
            contactInfoItems?: {
              showAddress?: boolean | null;
              showPhone?: boolean | null;
              showEmail?: boolean | null;
              showWorkingHours?: boolean | null;
              showSocial?: boolean | null;
            };
            showMap?: boolean | null;
            mapPosition?: ('top' | 'bottom' | 'side') | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            variant?: ('centered' | 'split' | 'with-image' | 'gradient' | 'minimal' | 'floating' | 'with-form') | null;
            headline: string;
            subheadline?: string | null;
            image?: (string | null) | Media;
            buttons?:
              | {
                  label: string;
                  link: string;
                  variant?: ('default' | 'outline' | 'ghost') | null;
                  id?: string | null;
                }[]
              | null;
            showPhoneNumber?: boolean | null;
            backgroundColor?: ('default' | 'light' | 'dark' | 'primary' | 'accent') | null;
            textAlignment?: ('left' | 'center' | 'right') | null;
            size?: ('small' | 'medium' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            variant?: ('grid-3' | 'grid-4' | 'masonry' | 'carousel' | 'lightbox' | 'instagram') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('custom' | 'portfolio') | null;
            limit?: number | null;
            images?:
              | {
                  image: string | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            showCaptions?: boolean | null;
            aspectRatio?: ('auto' | 'square' | '4-3' | '16-9' | '3-2') | null;
            gap?: ('none' | 'small' | 'medium' | 'large') | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            variant?: ('inline' | 'grid-4' | 'grid-3' | 'with-icons' | 'animated' | 'minimal') | null;
            heading?: string | null;
            source?: ('businessInfo' | 'custom') | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  icon?: string | null;
                  /**
                   * Ex: +, %, ani
                   */
                  suffix?: string | null;
                  id?: string | null;
                }[]
              | null;
            animated?: boolean | null;
            backgroundColor?: ('default' | 'light' | 'dark' | 'primary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            columns?:
              | {
                  width?: ('full' | 'three-quarters' | 'two-thirds' | 'half' | 'one-third' | 'one-quarter') | null;
                  alignment?: ('top' | 'center' | 'bottom') | null;
                  contentType?: ('richText' | 'image' | 'video') | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  image?: (string | null) | Media;
                  videoUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
            paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            variant?: ('grid-4' | 'grid-3' | 'carousel' | 'list' | 'featured') | null;
            heading?: string | null;
            subheading?: string | null;
            source?: ('collection' | 'manual') | null;
            selectedProducts?: (string | Product)[] | null;
            filterByCategory?: (string | null) | Category;
            limit?: number | null;
            onlyFeatured?: boolean | null;
            onlySale?: boolean | null;
            showPrice?: boolean | null;
            showSalePrice?: boolean | null;
            showAddToCart?: boolean | null;
            ctaButton?: {
              enabled?: boolean | null;
              label?: string | null;
              link?: string | null;
            };
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'products';
          }
        | {
            variant?: ('full-width' | 'contained' | 'with-info') | null;
            heading?: string | null;
            source?: ('businessInfo' | 'custom') | null;
            customEmbed?: string | null;
            height?: ('small' | 'medium' | 'large') | null;
            showDirectionsButton?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'map';
          }
        | {
            variant?: ('standard' | 'with-service' | 'with-person' | 'full' | 'minimal') | null;
            heading?: string | null;
            subheading?: string | null;
            showServiceSelection?: boolean | null;
            showTeamSelection?: boolean | null;
            showDatePicker?: boolean | null;
            showTimePicker?: boolean | null;
            requiredFields?: {
              name?: boolean | null;
              email?: boolean | null;
              phone?: boolean | null;
              notes?: boolean | null;
            };
            submitButtonText?: string | null;
            successMessage?: string | null;
            showWhatsappOption?: boolean | null;
            showPhoneOption?: boolean | null;
            backgroundColor?: ('default' | 'light' | 'dark' | 'primary') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'booking';
          }
        | {
            variant?: ('full' | 'compact') | null;
            heading?: string | null;
            showQuantitySelector?: boolean | null;
            showRemoveButton?: boolean | null;
            showSubtotal?: boolean | null;
            checkoutButtonText?: string | null;
            checkoutLink?: string | null;
            emptyCartMessage?: string | null;
            continueShoppingLink?: string | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cart';
          }
        | {
            variant?: ('full' | 'compact') | null;
            heading?: string | null;
            showOrderSummary?: boolean | null;
            showShippingOptions?: boolean | null;
            showPaymentOptions?: boolean | null;
            submitButtonText?: string | null;
            successMessage?: string | null;
            backgroundColor?: ('default' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkout';
          }
      )[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  /**
   * Maxim 2-3 propozitii pentru carduri
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Ex: Scissors, Heart, Car, Wrench, etc.
   */
  icon?: string | null;
  price?: number | null;
  priceFrom?: boolean | null;
  /**
   * Ex: 30 min, 1 ora, 2-3 ore
   */
  duration?: string | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  category?: (string | null) | Category;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  description?: string | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  name: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  role: string;
  image?: (string | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ex: 10+ ani experienta
   */
  experience?: string | null;
  specializations?:
    | {
        specialization?: string | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  schedule?:
    | {
        day?: ('luni' | 'marti' | 'miercuri' | 'joi' | 'vineri' | 'sambata' | 'duminica') | null;
        /**
         * Ex: 09:00 - 17:00 sau Inchis
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  role?: string | null;
  image?: (string | null) | Media;
  content: string;
  rating?: ('5' | '4' | '3' | '2' | '1') | null;
  service?: (string | null) | Service;
  source?: ('google' | 'facebook' | 'website' | 'other') | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-packages".
 */
export interface PricePackage {
  id: string;
  title: string;
  /**
   * Ex: Cel mai popular, Recomandat pentru incepatori
   */
  subtitle?: string | null;
  description?: string | null;
  price: number;
  /**
   * Pentru reduceri
   */
  oldPrice?: number | null;
  period?: ('luna' | 'an' | 'unic' | 'sedinta' | 'ora' | 'zi') | null;
  features?:
    | {
        feature: string;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    link?: string | null;
  };
  /**
   * Va fi evidentiat vizual
   */
  highlighted?: boolean | null;
  highlightLabel?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (string | null) | Media;
  gallery?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  client?: string | null;
  location?: string | null;
  completedAt?: string | null;
  services?: (string | Service)[] | null;
  testimonial?: {
    content?: string | null;
    author?: string | null;
  };
  category?: (string | null) | Category;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: (string | null) | Category;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  category?: (string | null) | ProductCategory;
  price: number;
  salePrice?: number | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInRONEnabled?: boolean | null;
  priceInRON?: number | null;
  badge?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  description?: string | null;
  image?: (string | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInRONEnabled?: boolean | null;
  priceInRON?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * URL-ul paginii (generat automat din titlu)
   */
  slug: string;
  /**
   * Scurta descriere pentru listari si SEO
   */
  excerpt?: string | null;
  featuredImage?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (string | null) | Category;
  author?: (string | null) | User;
  publishedAt?: string | null;
  relatedPosts?: (string | Post)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
  service: string | Service;
  teamMember?: (string | null) | Team;
  date: string;
  /**
   * Ex: 14:00
   */
  time: string;
  duration?: string | null;
  notes?: string | null;
  /**
   * Vizibile doar pentru personal
   */
  internalNotes?: string | null;
  status?: ('pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled' | 'no-show') | null;
  source?: ('website' | 'phone' | 'whatsapp' | 'facebook' | 'walkin') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  service?: (string | null) | Service;
  status?: ('new' | 'read' | 'replied' | 'resolved' | 'spam') | null;
  internalNotes?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Trebuie sa reconstruiesti site-ul dupa modificarea acestui camp.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  categories?:
    | {
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'RON' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'RON' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'RON' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: string | Portfolio;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'price-packages';
        value: string | PricePackage;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'faq';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroType?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        image?: T;
        videoUrl?: T;
        ctaButtons?:
          | T
          | {
              label?: T;
              link?: T;
              variant?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              image?: T;
              videoUrl?: T;
              slides?:
                | T
                | {
                    image?: T;
                    headline?: T;
                    subheadline?: T;
                    id?: T;
                  };
              ctaButtons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              overlayOpacity?: T;
              textColor?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedServices?: T;
              filterByCategory?: T;
              limit?: T;
              onlyFeatured?: T;
              customServices?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    image?: T;
                    price?: T;
                    link?: T;
                    id?: T;
                  };
              showPrices?: T;
              showIcons?: T;
              ctaButton?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    link?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedMembers?: T;
              limit?: T;
              onlyFeatured?: T;
              showRole?: T;
              showBio?: T;
              showSocial?: T;
              showContact?: T;
              columns?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedTestimonials?: T;
              limit?: T;
              onlyFeatured?: T;
              showRating?: T;
              showAvatar?: T;
              showSource?: T;
              autoplay?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedPackages?: T;
              limit?: T;
              showFeatures?: T;
              showOldPrice?: T;
              ctaText?: T;
              disclaimer?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        portfolio?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedProjects?: T;
              filterByCategory?: T;
              limit?: T;
              onlyFeatured?: T;
              showDescription?: T;
              showClient?: T;
              columns?: T;
              ctaButton?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    link?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedFAQs?: T;
              filterByCategory?: T;
              limit?: T;
              customFAQs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              defaultOpen?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              showForm?: T;
              formFields?:
                | T
                | {
                    showName?: T;
                    showEmail?: T;
                    showPhone?: T;
                    showSubject?: T;
                    showService?: T;
                    showMessage?: T;
                  };
              submitButtonText?: T;
              successMessage?: T;
              showContactInfo?: T;
              contactInfoItems?:
                | T
                | {
                    showAddress?: T;
                    showPhone?: T;
                    showEmail?: T;
                    showWorkingHours?: T;
                    showSocial?: T;
                  };
              showMap?: T;
              mapPosition?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              image?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    link?: T;
                    variant?: T;
                    id?: T;
                  };
              showPhoneNumber?: T;
              backgroundColor?: T;
              textAlignment?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              limit?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              showCaptions?: T;
              aspectRatio?: T;
              gap?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              variant?: T;
              heading?: T;
              source?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    suffix?: T;
                    id?: T;
                  };
              animated?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              columns?:
                | T
                | {
                    width?: T;
                    alignment?: T;
                    contentType?: T;
                    richText?: T;
                    image?: T;
                    videoUrl?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              paddingTop?: T;
              paddingBottom?: T;
              id?: T;
              blockName?: T;
            };
        products?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              source?: T;
              selectedProducts?: T;
              filterByCategory?: T;
              limit?: T;
              onlyFeatured?: T;
              onlySale?: T;
              showPrice?: T;
              showSalePrice?: T;
              showAddToCart?: T;
              ctaButton?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    link?: T;
                  };
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              variant?: T;
              heading?: T;
              source?: T;
              customEmbed?: T;
              height?: T;
              showDirectionsButton?: T;
              id?: T;
              blockName?: T;
            };
        booking?:
          | T
          | {
              variant?: T;
              heading?: T;
              subheading?: T;
              showServiceSelection?: T;
              showTeamSelection?: T;
              showDatePicker?: T;
              showTimePicker?: T;
              requiredFields?:
                | T
                | {
                    name?: T;
                    email?: T;
                    phone?: T;
                    notes?: T;
                  };
              submitButtonText?: T;
              successMessage?: T;
              showWhatsappOption?: T;
              showPhoneOption?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        cart?:
          | T
          | {
              variant?: T;
              heading?: T;
              showQuantitySelector?: T;
              showRemoveButton?: T;
              showSubtotal?: T;
              checkoutButtonText?: T;
              checkoutLink?: T;
              emptyCartMessage?: T;
              continueShoppingLink?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
        checkout?:
          | T
          | {
              variant?: T;
              heading?: T;
              showOrderSummary?: T;
              showShippingOptions?: T;
              showPaymentOptions?: T;
              submitButtonText?: T;
              successMessage?: T;
              backgroundColor?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  image?: T;
  icon?: T;
  price?: T;
  priceFrom?: T;
  duration?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  category?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  image?: T;
  bio?: T;
  experience?: T;
  specializations?:
    | T
    | {
        specialization?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  schedule?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  client?: T;
  location?: T;
  completedAt?: T;
  services?: T;
  testimonial?:
    | T
    | {
        content?: T;
        author?: T;
      };
  category?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  content?: T;
  rating?: T;
  service?: T;
  source?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-packages_select".
 */
export interface PricePackagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  price?: T;
  oldPrice?: T;
  period?: T;
  features?:
    | T
    | {
        feature?: T;
        included?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  highlighted?: T;
  highlightLabel?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  clientName?: T;
  clientEmail?: T;
  clientPhone?: T;
  service?: T;
  teamMember?: T;
  date?: T;
  time?: T;
  duration?: T;
  notes?: T;
  internalNotes?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  service?: T;
  status?: T;
  internalNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInRONEnabled?: T;
  priceInRON?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  price?: T;
  salePrice?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInRONEnabled?: T;
  priceInRON?: T;
  badge?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  variant?: ('standard' | 'centered' | 'with-topbar' | 'transparent' | 'minimal') | null;
  topBar?: {
    showPhone?: boolean | null;
    showEmail?: boolean | null;
    showSocial?: boolean | null;
    showWorkingHours?: boolean | null;
    /**
     * Ex: Transport gratuit la comenzi peste 200 lei
     */
    customText?: string | null;
  };
  navItems?:
    | {
        label: string;
        type?: ('reference' | 'custom') | null;
        reference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        url?: string | null;
        newTab?: boolean | null;
        hasSubmenu?: boolean | null;
        submenu?:
          | {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              url?: string | null;
              newTab?: boolean | null;
              description?: string | null;
              icon?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showSearch?: boolean | null;
  showCart?: boolean | null;
  ctaButton?: {
    enabled?: boolean | null;
    label?: string | null;
    link?: string | null;
    variant?: ('default' | 'outline' | 'ghost') | null;
  };
  sticky?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  variant?: ('columns-4' | 'columns-3' | 'minimal' | 'centered' | 'with-newsletter' | 'with-map') | null;
  columns?:
    | {
        title?: string | null;
        type?: ('links' | 'contact' | 'schedule' | 'text' | 'social') | null;
        links?:
          | {
              label: string;
              type?: ('reference' | 'custom') | null;
              reference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
  };
  showSocialLinks?: boolean | null;
  showContactInfo?: boolean | null;
  showWorkingHours?: boolean | null;
  /**
   * Foloseste {year} pentru an si {businessName} pentru numele afacerii
   */
  copyright?: string | null;
  legalLinks?:
    | {
        label: string;
        type?: ('reference' | 'custom') | null;
        reference?: {
          relationTo: 'pages';
          value: string | Page;
        } | null;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  showPaymentIcons?: boolean | null;
  paymentMethods?: ('visa' | 'mastercard' | 'paypal' | 'cash' | 'bank')[] | null;
  badges?:
    | {
        image?: (string | null) | Media;
        link?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: string;
  preset?: ('modern' | 'classic' | 'bold' | 'elegant' | 'minimal' | 'custom') | null;
  colors?: {
    primary?: string | null;
    secondary?: string | null;
    accent?: string | null;
    dark?: string | null;
    light?: string | null;
    surface?: string | null;
    text?: string | null;
    textLight?: string | null;
    border?: string | null;
  };
  fontPreset?: ('modern' | 'elegant' | 'bold' | 'minimalist' | 'classic') | null;
  fonts?: {
    headingFont?: ('Inter' | 'Playfair Display' | 'Montserrat' | 'Poppins' | 'Geist' | 'Roboto') | null;
    bodyFont?: ('Inter' | 'Source Sans Pro' | 'Open Sans' | 'Roboto' | 'Geist' | 'Poppins') | null;
  };
  stylePreset?: ('modern' | 'classic' | 'bold' | 'minimal') | null;
  borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
  shadows?: ('none' | 'subtle' | 'moderate' | 'strong') | null;
  animations?: ('none' | 'subtle' | 'moderate' | 'dynamic') | null;
  containerWidth?: ('1024' | '1280' | '1400' | '1600') | null;
  sectionSpacing?: ('compact' | 'normal' | 'spacious') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo".
 */
export interface Logo {
  id: string;
  type?: ('text' | 'image' | 'both') | null;
  text?: string | null;
  image?: (string | null) | Media;
  /**
   * Pentru utilizare pe fundal deschis (optional)
   */
  imageDark?: (string | null) | Media;
  /**
   * Pentru utilizare pe fundal inchis (optional)
   */
  imageLight?: (string | null) | Media;
  /**
   * Icon-ul care apare in tab-ul browser-ului (32x32 sau 64x64)
   */
  favicon?: (string | null) | Media;
  size?: {
    height?: number | null;
    heightMobile?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info".
 */
export interface BusinessInfo {
  id: string;
  name: string;
  /**
   * Ex: Frumusete cu pasiune de peste 10 ani
   */
  tagline?: string | null;
  /**
   * Folosit pentru SEO si despre noi
   */
  description?: string | null;
  yearEstablished?: number | null;
  address?: {
    street?: string | null;
    city?: string | null;
    county?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  phoneSecondary?: string | null;
  email?: string | null;
  whatsapp?: string | null;
  workingHours?:
    | {
        /**
         * Ex: Luni - Vineri
         */
        days?: string | null;
        /**
         * Ex: 09:00 - 18:00 sau Inchis
         */
        hours?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  /**
   * Copiaza codul iframe de la Google Maps
   */
  googleMapsEmbed?: string | null;
  /**
   * Link direct catre locatie pe Google Maps
   */
  googleMapsLink?: string | null;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Ex: 10+ ani experienta, 500+ clienti, etc.
   */
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  legal?: {
    companyName?: string | null;
    cui?: string | null;
    regCom?: string | null;
    bankAccount?: string | null;
    bank?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configureaza functionalitatea de magazin/cos cumparaturi
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: string;
  /**
   * Activeaza functionalitatea de magazin cu cos de cumparaturi
   */
  enabled?: boolean | null;
  /**
   * Ex: Magazin Online, Shop, Produse
   */
  shopName?: string | null;
  currency?: ('RON' | 'EUR' | 'USD') | null;
  /**
   * Ex: lei, €, $
   */
  currencySymbol?: string | null;
  pricePosition?: ('before' | 'after') | null;
  /**
   * Valoarea minima pentru a putea plasa comanda. Lasa gol pentru fara minim.
   */
  orderMinimum?: number | null;
  /**
   * Valoarea de la care transportul devine gratuit. Lasa gol daca nu se aplica.
   */
  freeShippingThreshold?: number | null;
  shippingCost?: number | null;
  paymentMethods?:
    | {
        method: 'cod' | 'stripe' | 'bank';
        enabled?: boolean | null;
        /**
         * Instructiuni afisate clientului pentru aceasta metoda
         */
        instructions?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Adresa unde primesti notificari pentru comenzi noi
   */
  orderNotificationEmail?: string | null;
  /**
   * Trimite email de confirmare automat catre client
   */
  sendCustomerConfirmation?: boolean | null;
  confirmationEmailSubject?: string | null;
  addToCartText?: string | null;
  viewCartText?: string | null;
  checkoutText?: string | null;
  emptyCartMessage?: string | null;
  orderSuccessMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Schimba rapid aspectul site-ului selectand o varianta predefinita
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variant".
 */
export interface DesignVariant {
  id: string;
  /**
   * Selecteaza tipul de afacere pentru a vedea variantele disponibile
   */
  businessType:
    | 'barbershop'
    | 'dentist'
    | 'restaurant'
    | 'magazin'
    | 'auto-service'
    | 'salon'
    | 'avocat'
    | 'constructii';
  /**
   * Fiecare varianta are culori, fonturi si layout diferit
   */
  variantIndex: '0' | '1' | '2' | '3' | '4';
  /**
   * Informatii despre varianta selectata
   */
  variantDescription?: string | null;
  useOverride?: boolean | null;
  override?: {
    heroType?: ('fullscreen' | 'centered' | 'split' | 'minimal') | null;
    heroOverlay?: ('dark' | 'light' | 'gradient' | 'none') | null;
    servicesVariant?: ('grid-3' | 'grid-4' | 'list' | 'cards' | 'with-prices') | null;
    teamVariant?: ('grid' | 'grid-centered' | 'list' | 'carousel') | null;
    testimonialsVariant?: ('carousel' | 'grid' | 'masonry' | 'single') | null;
    galleryVariant?: ('grid-3' | 'grid-4' | 'masonry' | 'carousel') | null;
  };
  /**
   * Trage pentru a reordona sectiunile pe homepage
   */
  homepageSections?:
    | {
        section:
          | 'hero'
          | 'services'
          | 'products'
          | 'stats'
          | 'team'
          | 'testimonials'
          | 'gallery'
          | 'faq'
          | 'pricing'
          | 'cta'
          | 'contact';
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  variant?: T;
  topBar?:
    | T
    | {
        showPhone?: T;
        showEmail?: T;
        showSocial?: T;
        showWorkingHours?: T;
        customText?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
        newTab?: T;
        hasSubmenu?: T;
        submenu?:
          | T
          | {
              label?: T;
              type?: T;
              reference?: T;
              url?: T;
              newTab?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  showSearch?: T;
  showCart?: T;
  ctaButton?:
    | T
    | {
        enabled?: T;
        label?: T;
        link?: T;
        variant?: T;
      };
  sticky?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  variant?: T;
  columns?:
    | T
    | {
        title?: T;
        type?: T;
        links?:
          | T
          | {
              label?: T;
              type?: T;
              reference?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        text?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
      };
  showSocialLinks?: T;
  showContactInfo?: T;
  showWorkingHours?: T;
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        type?: T;
        reference?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  showPaymentIcons?: T;
  paymentMethods?: T;
  badges?:
    | T
    | {
        image?: T;
        link?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  preset?: T;
  colors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
        dark?: T;
        light?: T;
        surface?: T;
        text?: T;
        textLight?: T;
        border?: T;
      };
  fontPreset?: T;
  fonts?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
      };
  stylePreset?: T;
  borderRadius?: T;
  shadows?: T;
  animations?: T;
  containerWidth?: T;
  sectionSpacing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logo_select".
 */
export interface LogoSelect<T extends boolean = true> {
  type?: T;
  text?: T;
  image?: T;
  imageDark?: T;
  imageLight?: T;
  favicon?: T;
  size?:
    | T
    | {
        height?: T;
        heightMobile?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-info_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  yearEstablished?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        county?: T;
        postalCode?: T;
        country?: T;
      };
  phone?: T;
  phoneSecondary?: T;
  email?: T;
  whatsapp?: T;
  workingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        linkedin?: T;
        twitter?: T;
      };
  googleMapsEmbed?: T;
  googleMapsLink?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  legal?:
    | T
    | {
        companyName?: T;
        cui?: T;
        regCom?: T;
        bankAccount?: T;
        bank?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  enabled?: T;
  shopName?: T;
  currency?: T;
  currencySymbol?: T;
  pricePosition?: T;
  orderMinimum?: T;
  freeShippingThreshold?: T;
  shippingCost?: T;
  paymentMethods?:
    | T
    | {
        method?: T;
        enabled?: T;
        instructions?: T;
        id?: T;
      };
  orderNotificationEmail?: T;
  sendCustomerConfirmation?: T;
  confirmationEmailSubject?: T;
  addToCartText?: T;
  viewCartText?: T;
  checkoutText?: T;
  emptyCartMessage?: T;
  orderSuccessMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variant_select".
 */
export interface DesignVariantSelect<T extends boolean = true> {
  businessType?: T;
  variantIndex?: T;
  variantDescription?: T;
  useOverride?: T;
  override?:
    | T
    | {
        heroType?: T;
        heroOverlay?: T;
        servicesVariant?: T;
        teamVariant?: T;
        testimonialsVariant?: T;
        galleryVariant?: T;
      };
  homepageSections?:
    | T
    | {
        section?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}